#NOTE: This script is used to simulate the computational model presented
#in Ballard, Palada, Griffin, and Neal (2018).

### clear workspace ###
rm(list = ls())

### load packages ###
library(tidyverse)

### simulation setup ###

n_episodes = 10                      #number of goal pursuit episodes
n_timesteps = 5                      #number of time steps per episode
n_total = n_episodes * n_timesteps   #number of total timesteps

### set parameter values for simulation ###

goal_0 = 4         #initial goal level
theta = 0.5        #sensitivity of goal adjustment to previous gpd
lambda = 0         #bias in goal adjustment due to risk preference

effort_0 = 7       #initial effort
effort_bl = 4      #effort baseline
alpha = 0.1        #rate at which effort returns to baseline
beta = 0.1         #sensitivity of effort adjustment to change in gpd

skill_0 = 0        #initial skill level
skill_max = 3      #maximum skill level achievable
delta = 0.1        #learning rate

performance_0 = 0  #initial level of performance variable (0 in our task)
kappa = 1          #steepness of effort-performance function
gamma = 5          #location of effort-performance function

### initialize variables that serve as inputs to the simulation ###

episode = rep(1:n_episodes, each = n_timesteps)
time = rep(1:n_timesteps, times = n_episodes)
practice = 1:n_total

### initialize variables that are generated by the simulation ###
goal = rep(NA, n_total)
effort = rep(NA, n_total)
skill = rep(NA, n_total)
performance = rep(NA, n_total)
gpd = rep(NA, n_total)

### run simulation ###
for (i in 1:n_total) {
  ##### CALCULATE GOAL LEVEL #####
  if (time[i] == 1) {
    #goal is updated only on the first timestep of the goal striving episode.

    if (episode[i] == 1) {
      # If the first goal striving episode, goal is equal to initial goal parameter.
      # This is because there are no previous values of the goal and performance variables,
      # which are needed for calculating change in goal. Thus, we just treat goal at the first
      # episode as a prespecified parameter.
      goal[i] = goal_0
    }

    if (episode[i] > 1) {
      #if not the first episode, the change in goal level is calculated according to Equation 2.
      change_in_goal = theta * (performance[i - 1] - goal[i - 1]) + lambda
      goal[i] = goal[i - 1] + change_in_goal
    }
  }

  if (time[i] > 1) {
    #if it is not the first time step of the goal striving episode, the goal cannot be updated,
    #so the goal level retains its previous value.
    goal[i] = goal[i - 1]
  }

  ##### CALCULATE EFFORT #####

  if (time[i] == 1) {
    # if start of goal striving episode, effort is equal to the initial effort parameter.
    # This is because there are no previous values of the effort and gpd variables,
    # which are needed for calculating change in effort. Thus, we just treat effort at the first
    # time point within each episode as a prespecified parameter.

    effort[i] = effort_0

    # gpd needs to be stored in order to determine subsequent levels of effort.
    # Here, gpd represents the goal-performance discrepancy *before* the first time step.
    # In this case, the performance variable has not yet had time to accrue,
    # so gpd is just equal to the goal.

    gpd[i] = goal[i]
  }

  if (time[i] > 1) {
    #if not start of goal striving episode, the change in effort is calculated according to Equation 1.

    gpd[i] = goal[i] - performance[i - 1]

    change_in_effort = alpha * (effort_bl - effort[i - 1]) + beta * (gpd[i] -
                                                                       gpd[i - 1])
    effort[i] = effort[i - 1] + change_in_effort
  }

  ##### CALCULATE SKILL #####

  #skill is determined according to Equation 2.
  skill[i] = skill_max - (skill_max - skill_0) * exp(-delta * practice[i])


  ##### CALCULATE PERFORMANCE #####

  #the change in performance is calculated according to Equation 4
  change_in_performance = skill[i] / (1 + exp(-kappa * (effort[i] - gamma)))


  if (time[i] == 1) {
    # if start of goal striving episode, performance is just equal to the change in performance for
    # that time window plus the initial performance.
    performance[i] = performance_0 + change_in_performance
  }

  if (time[i] > 1) {
    # if not start of goal striving episode, performance is incremented based on its previous value (according to Equation 3)
    performance[i] = performance[i - 1] + change_in_performance
  }
}


### store variables in data frame ###

output = tibble(episode, time, practice, gpd, goal, effort, skill, performance) %>%
  gather(variable, level, goal:performance)

### graph simulation results ###

ggplot(output) +
  geom_line(aes(x = time, y = level)) +
  facet_grid(variable ~ episode)
